#!/usr/bin/env python3
"""
Fix QGIS Python environment by creating a startup script.

This script creates ~/.local/share/QGIS/QGIS3/profiles/default/python/startup.py
which adds /usr/lib/python3/dist-packages to sys.path so QGIS can find its bindings.
"""

import os
import sys
from pathlib import Path

def create_qgis_startup_script():
    """Create QGIS startup script to fix Python path."""
    qgis_profile_dir = Path.home() / ".local" / "share" / "QGIS" / "QGIS3" / "profiles" / "default" / "python"
    qgis_profile_dir.mkdir(parents=True, exist_ok=True)
    
    startup_script = qgis_profile_dir / "startup.py"
    
    script_content = '''"""
QGIS Startup Script - Auto-generated by Phase 1 setup

This script fixes the Python path so QGIS can find its Python bindings.
It adds /usr/lib/python3/dist-packages to sys.path and ensures PyQt5.sip is available.
"""

import sys
import os

# Add system dist-packages to Python path (where QGIS bindings are installed)
dist_packages = "/usr/lib/python3/dist-packages"
if dist_packages not in sys.path:
    sys.path.insert(0, dist_packages)

# Ensure PyQt5.sip is available (required by QGIS)
try:
    import PyQt5.sip
except ImportError:
    # Try to find PyQt5 in dist-packages
    pyqt5_path = os.path.join(dist_packages, "PyQt5")
    if os.path.exists(pyqt5_path) and pyqt5_path not in sys.path:
        sys.path.insert(0, pyqt5_path)
    try:
        import PyQt5.sip
    except ImportError:
        print("Warning: PyQt5.sip not found. QGIS Python console may not work fully.")
        print("This doesn't affect QGIS GUI functionality.")

# Verify qgis module can be imported
try:
    import qgis.core
    print("✓ QGIS Python bindings loaded successfully")
except ImportError as e:
    print(f"Warning: Could not import qgis.core: {e}")
    print("QGIS GUI will still work, but Python console may be limited.")
'''
    
    startup_script.write_text(script_content)
    print(f"✓ Created QGIS startup script: {startup_script}")
    print("")
    print("Next steps:")
    print("1. Close QGIS if it's open")
    print("2. Restart QGIS")
    print("3. The SIP error should be gone!")
    print("")
    print("To verify, open QGIS Python console (Plugins -> Python Console)")
    print("and type: import qgis.core")
    print("It should work without errors.")
    
    return startup_script

if __name__ == "__main__":
    create_qgis_startup_script()
