#!/usr/bin/env python3
"""
Fix QGIS Python environment - Enhanced version with debug output.

This creates a startup script that QGIS will load, with debug output
to help diagnose issues.
"""

import os
import sys
from pathlib import Path

def create_enhanced_startup_script():
    """Create enhanced QGIS startup script with debug output."""
    qgis_profile_dir = Path.home() / ".local" / "share" / "QGIS" / "QGIS3" / "profiles" / "default" / "python"
    qgis_profile_dir.mkdir(parents=True, exist_ok=True)
    
    startup_script = qgis_profile_dir / "startup.py"
    
    script_content = '''"""
QGIS Startup Script - Auto-generated by Phase 1 setup (Enhanced)

This script fixes the Python path so QGIS can find its Python bindings.
It adds /usr/lib/python3/dist-packages to sys.path and ensures PyQt5.sip is available.

Debug output will appear in QGIS Python console when this script runs.
"""

import sys
import os

# Debug: Print initial state
print("=" * 60)
print("QGIS Startup Script Running...")
print(f"Python version: {sys.version}")
print(f"Initial sys.path length: {len(sys.path)}")

# Add system dist-packages to Python path (where QGIS bindings are installed)
dist_packages = "/usr/lib/python3/dist-packages"
if dist_packages not in sys.path:
    sys.path.insert(0, dist_packages)
    print(f"✓ Added {dist_packages} to sys.path")
else:
    print(f"✓ {dist_packages} already in sys.path")

# Ensure PyQt5.sip is available (required by QGIS)
try:
    import PyQt5.sip
    print("✓ PyQt5.sip imported successfully")
except ImportError as e:
    print(f"⚠ Warning: Could not import PyQt5.sip: {e}")
    # Try to find PyQt5 in dist-packages
    pyqt5_path = os.path.join(dist_packages, "PyQt5")
    if os.path.exists(pyqt5_path) and pyqt5_path not in sys.path:
        sys.path.insert(0, pyqt5_path)
        print(f"  Added {pyqt5_path} to sys.path")
    try:
        import PyQt5.sip
        print("  ✓ PyQt5.sip imported after path fix")
    except ImportError as e2:
        print(f"  ❌ Still failed to import PyQt5.sip: {e2}")
        print("  Note: This doesn't affect QGIS GUI functionality.")

# Verify qgis module can be imported
try:
    import qgis.core
    print("✓ qgis.core imported successfully!")
    print(f"  QGIS version: {qgis.core.Qgis.QGIS_VERSION}")
    print("=" * 60)
    print("✓ QGIS Python bindings are ready!")
except ImportError as e:
    print(f"❌ Could not import qgis.core: {e}")
    print("=" * 60)
    print("⚠ QGIS GUI will still work, but Python console may be limited.")
    print("  Check that python3-qgis is installed:")
    print("    dpkg -l | grep python3-qgis")
except Exception as e:
    print(f"❌ Unexpected error importing qgis.core: {e}")
    print("=" * 60)
'''
    
    startup_script.write_text(script_content)
    print(f"✓ Created enhanced QGIS startup script: {startup_script}")
    print("")
    print("The script now includes debug output that will appear in QGIS Python console.")
    print("")
    print("Next steps:")
    print("1. Close QGIS completely if it's open")
    print("2. Restart QGIS")
    print("3. Open Python Console (Plugins -> Python Console)")
    print("4. You should see debug output showing the fix is working")
    print("5. Try: import qgis.core")
    print("")
    
    return startup_script

if __name__ == "__main__":
    create_enhanced_startup_script()
